Gemfile.lock, db/migrate/20220301103018_add_avatar_to_users.rb, db/schema.rb
=> add avatar_urm column to users

Gemfile.lock, app/models/user.rb, db/seeds.rb
Added seed for Users, Tasks and one garden
=> User seeds

Gemfile.lock, app/controllers/select_tasks_controller.rb, app/controllers/tasks_controller.rb, app/views/select_tasks/index.html.erb, app/views/select_tasks/new.html.erb, app/views/tasks/index.html.erb, config/routes.rb
create select tasks and task features +views
=> Task features

app/views/shared/_navbar.html.erb
=> Add links to navbar

db/seeds.rb
=> added hardcode garden_users to seed

app/controllers/garden_users_controller.rb, app/controllers/pages_controller.rb, app/views/garden_users/_index.html.erb, app/views/gardens/index.html.erb, app/views/select_tasks/_index.html.erb
…rent user is apart of. Added users tasks to dashboard
=> Garden will display the right users now. Can only see the gardens current user is apart of. Added users tasks to dashboard.

app/controllers/select_tasks_controller.rb, app/javascript/controllers/checkbox_controller.js, app/models/user.rb, app/views/garden_users/_index.html.erb, app/views/select_tasks/_index.html.erb, app/views/select_tasks/new.html.erb, config/routes.rb
user can delete a selected task and mark it as done and gain some xp
=> user can delete a selected task and mark it as done and gain xp

db/migrate/20220302142036_add_column_plant_url_to_users.rb, db/schema.rb, db/seeds.rb
add table plant url to user table + fix seeds
=> add plant url to user table

app/assets/stylesheets/components/_dashboard_menu.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/views/pages/dashboard.html.erb, app/views/shared/_bottom_menu.html.erb
adding color palette to color.scss + starting design menu
=> Dashboard basic design

app/controllers/pages_controller.rb, app/views/garden_users/_index.html.erb, app/views/select_tasks/_index.html.erb
…last completed tasks. Added active members
=> User can now see their last 5 completed tasks as well as other users completed tasks. Added active members in current garden.

app/assets/stylesheets/components/_dashboard_menu.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_xp_bar.scss, app/assets/stylesheets/pages/_dashboard.scss, app/javascript/controllers/xpbar_controller.js, app/views/dashboard_partials/_bottom_menu.html.erb, app/views/dashboard_partials/_user_plant.html.erb, app/views/dashboard_partials/_user_plant_info.html.erb, app/views/pages/dashboard.html.erb
fixing js issues + fixed plant on the ground in the dashboard
=> fixing dashboard issues + make the plant stick to the ground

app/assets/stylesheets/components/_dashboard_menu.scss, app/views/dashboard_partials/_completedTasks.html.erb
add color to bottom menu
fix plants to ground
=> added color to bottom menu

app/assets/stylesheets/pages/_dashboard.scss, app/views/dashboard_partials/_selectedTasks.html.erb
=> first design selected tasks

app/assets/stylesheets/components/_dashboard_menu.scss, app/assets/stylesheets/components/_user_garden_list.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/dashboard_partials/_gardenMembers.html.erb, app/views/dashboard_partials/_selectedTasks.html.erb, app/views/dashboard_partials/_user_plant_info.html.erb, app/views/dashboard_partials/_users_garden_list.html.erb, app/views/pages/dashboard.html.erb
fixing lvl + memeber list basic design
=> fixing lvl

app/assets/stylesheets/components/_dashboard_menu.scss, app/assets/stylesheets/components/_ground.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/dashboard_partials/_user_plant.html.erb, app/views/garden_users/_lvlup_plant.html.erb
fixing plant size in the garden and in the bottom menu'
=> fixing plant size in the garden and in the bottom menu

app/assets/stylesheets/components/_ground.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal_tasks.scss, app/assets/stylesheets/pages/_dashboard.scss
=> Dashboard plant size

app/assets/stylesheets/components/_ground.scss, app/assets/stylesheets/components/_navbar.scss
changed color of nav bar background in dropdown
=> changed navbar background

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_dashboard_menu.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_dashboard.scss, app/controllers/pages_controller.rb, app/views/dashboard_partials/_modal.html.erb, app/views/dashboard_partials/_users_garden_list.html.erb, app/views/select_tasks/new.html.erb
resize user's garden list + background transparent + background stransparent for selected tasks
=> fixed size for garden users + make it transparent

app/assets/stylesheets/components/_selected_tasks.scss, app/assets/stylesheets/pages/_dashboard.scss
=> fix color issus with tasks

app/assets/stylesheets/components/_dashboard_menu.scss, app/assets/stylesheets/components/_selected_tasks.scss, app/views/dashboard_partials/_selectedTasks.html.erb
add footer to tasks list + fixed position for water + hover
=> Selected tasks design

app/views/shared/_navbar.html.erb
add join garden, add a friend, create a new garden to navbar
=> add join garden, add a friend, create a new garden

app/assets/stylesheets/components/_ground.scss, app/views/dashboard_partials/_user_plant.html.erb
add glow effect to the current user plant + changed color of the name
=> added glow effect on current user plant

app/assets/stylesheets/components/_modal_tasks.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb
=> fix home page button
